export const NavigationScreens = {
    SplashScreen: 'Splash Screen',
    LoginScreen: 'Login Screen',
    BarcodeScannerScreen: 'Barcode Scanner Screen',
    BestSellersScreen: 'BestSellers Screen',
    SlowMoversScreen: 'SlowMovers Screen',
    WatchlistScreen: 'Watchlist Screen',
    ProductScreen: 'Product Screen',
    BottomTab: 'Bottom Tab',
    DashboardScreen: 'Dashboard Screen',
    AddItemsScreen: 'Add Items Screen',
    ItemMovementScreen: 'Item Movement Screen',
    ManageStockScreen: 'Manage Stock Screen',
    GeneratePOScreen: 'Generate PO Screen',
    AlertsScreen: 'Alerts Screen',
    PredictionsScreen: 'Predictions Screen',
    SearchScreen: "Search Screen",
    ProductScannerScreen: 'Product Scanner Screen',
    ScanHistoryScreen: 'Scan History Screen',
}

export const keyboardType = {
    ascii_capable: 'ascii-capable',
    decimal_pad: 'decimal-pad',
    default: 'default',
    email_address: 'email-address',
    name_phone_pad: 'name-phone-pad',
    number_pad: 'number-pad',
    numbers_and_punctuation: 'numbers-and-punctuation',
    numeric: 'numeric',
    phone_pad: 'phone-pad',
    twitter: 'twitter',
    url: 'url',
    visible_password: 'visible-password',
    web_search: 'web-search',
}