export const FETCH_AUTH_ID = "FETCH_AUTH_ID";
export const REMOVE_AUTH_ID = "REMOVE_AUTH_ID";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";

export const FETCH_STORE_DATA = "FETCH_STORE_DATA";
export const REMOVE_STORE_DATA = "REMOVE_STORE_DATA";

export const FETCH_LOCATION_STORE_DATA = "FETCH_LOCATION_STORE_DATA";
export const REMOVE_LOCATION_STORE_DATA = "REMOVE_LOCATION_STORE_DATA";

export const FETCH_SELECTED_STORE_DATA = "FETCH_SELECTED_STORE_DATA";
export const REMOVE_SELECTED_STORE_DATA = "REMOVE_SELECTED_STORE_DATA";

export const FETCH_SELECTED_STORE_LOCATION_DATA = "FETCH_SELECTED_STORE_LOCATION_DATA";
export const REMOVE_SELECTED_STORE_LOCATION_DATA = "REMOVE_SELECTED_STORE_LOCATION_DATA";

export const FETCH_DEPARTMENT_DATA = "FETCH_DEPARTMENT_DATA";
export const REMOVE_DEPARTMENT_DATA = "REMOVE_DEPARTMENT_DATA";

export const FETCH_SCAN_DATA = "FETCH_SCAN_DATA";
export const REMOVE_SCAN_DATA = "REMOVE_SCAN_DATA";

export const FETCH_ISSUE_DATA = "FETCH_ISSUE_DATA";
export const REMOVE_ISSUE_DATA = "REMOVE_ISSUE_DATA";